### ISSUE TITLE
Test06 doesn't output sound

### ISSUE THREAD

**Issue by cdc143** [cdc143/CPSC-599#1]
The latest version works on my mac now

**Comment by ksmort** [comment]
Okay, thanks for letting me know!  Maybe we can try and figure it out together sometime soon!

**Comment by lucmichaud** [comment]
It makes sound on my machine (windows 10, amd64)

**Comment by ksmort** [comment]
Also got it working (redownloaded vice).  Those are some of the worst sounds I have ever heard, but yay sound.
