### ISSUE TITLE
Check new TODO and VIC testing tomorrow

### ISSUE THREAD

**Issue by cdc143** [cdc143/CPSC-599#10]
Luc and I have gone through and updated the TODO document. Mostly small things left that we've assigned to different people. Meet tomorrow at some point to test on VIC.

Meeting tomorrow morning at 11-12?

**Comment by ksmort** [comment]
Sounds good.  I have class 11-12 which I am going to try to go to because I'm feeling better, but I can meet 10-11 or 12-1, or anytime after 2.

**Comment by ksmort** [comment]
For damage and healing based on colour, are we changing the colour of the hearts to be different healing points or are you just referring to enemy attack points?

**Comment by cdc143** [comment]
The amount of health the enemy has. Also possibly coloring hearts
differently so they restore different amounts of health, but if you don't
get to that it's fine

**Comment by lucmichaud** [comment]
I think hearts being a single value is fine, our enemies are just purple at the moment with the new enemy spawning code.

**Comment by ksmort** [comment]
After trying to attend a half-day of school and feeling miserable, I'm going to skip my lecture tomorrow and should be free 11-12.

**Comment by cdc143** [comment]
Okay sounds good! The new enemy spawning code seems a bit glitchy. There was one enemy in a box, and when I moved down floors, there was like 50 enemies in that room for some reason. We also need to call that method every time we load a room as well. Our game is otherwise pretty playable, although its somewhat silly without moving enemies. Also, the changing colour on a new floor works, but it looks horrid. I think maybe it's just easier to increment only the wall color

**Comment by ksmort** [comment]
The changing colour is just leftover colour from the portal animation, but you are right in the sense that it would be immediately kicked off Project Runway. :P  I'll fix that up in a bit, shouldn't take long at all.

**Comment by lucmichaud** [comment]
I think variables from the header are getting destroyed on reload, not sure but the first time i spawn there are a normal amount of enemies and they are all an empty space, when I go back to the title screen and into the game they are all in the walls.

**Comment by lucmichaud** [comment]
Yeah they are now spawning in the walls, not sure lol

**Comment by cdc143** [comment]
I just kept whatever you had when I did the conflicting commit stuff.
There's probably a bug in the somewhere. I know we solved it on Friday by
changing things around and it finally was properly comparing to a space.
Sometimes you seem to get to many enemies as well, but that's probably just
some variable not being reset, because it never seems to happen in the
first room

On Dec 6, 2016 6:13 PM, "lucmichaud" <notifications@github.com> wrote:

Yeah they are now spawning in the walls, not sure lol

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cdc143/CPSC-599/issues/10#issuecomment-265325608>, or mute
the thread

**Comment by ksmort** [comment]
I think it's just not checking if the space is already occupied, and there's no bitmask/mod/smth to have only a certain amount of enemies?

**Comment by ksmort** [comment]
Who wants to bring their laptop for the demo, as per John's email?  I would normally offer mine but I've been coughing all over it the past few days; I can Purell it if needed.

**Comment by lucmichaud** [comment]
I don't have a laptop, could always remote into my pc from my phone XD

**Comment by ksmort** [comment]
:P  I can bring my laptop then, everyone's sick anyways.  I'll wipe down the keyboard before coming to class.

**Comment by ksmort** [comment]
I'm going to try to go to class tomorrow, so I won't be available 11-12 but will be available 12-1 and 2-3/3:30-end of day.  Basically until I lose my voice.

**Comment by cdc143** [comment]
I'd be okay with either. I'm going to get the custom character set going
and then maybe we can meet for a bit, fix up enemy movement and test it on
the Vic.

**Comment by lucmichaud** [comment]
Im going to be in the lab 11-1:30 ish
probably take lunch and will go to the vic lab to test if you guys are going

**Comment by cdc143** [comment]
Okay I’ll come for 11 and we can work on some stuff and try it out on the VIC.

**Comment by cdc143** [comment]
So the custom character set will take an additional 140 bytes to implement, which isn’t a problem since that leaves us with 469 bytes to do whatever we want. Hooray for no out of memory garbage :).

**Comment by ksmort** [comment]
I'll meet you guys at 12!

**Comment by cdc143** [comment]
I'm in zone 17 :)

**Comment by cdc143** [comment]
Everything works now, except for enemy movement. I tried to find Ettiene, but he wasn't around. Demo02-06 has everything going. If we get enemy movement working, that's awesome (It seems really close to working, but its buggy and I couldn't figure out exactly why).

**Comment by cdc143** [comment]
We could also just do random enemy movement (pick a direction at random and try to move there) might be easier

**Comment by lucmichaud** [comment]
I don't think the code for picking a direction is broken I think it's using the array that is the issue

**Comment by cdc143** [comment]
Alright well I'll hydrate, eat, take a small nap and then take another
gander. If we can't get it working, what should the backup plan be?

**Comment by lucmichaud** [comment]
well we can have one moving, also i thought i saw 2 moving on kiersten's computer >.> maybe it was a bug

**Comment by ksmort** [comment]
Probably a bug.  In that case, would we want our AI to eat walls still?

**Comment by cdc143** [comment]
I think I found part of the issue. Enemyypos isn't get inited properly. All 0s when I look in the monitor. enemyxpos is okay though.

**Comment by lucmichaud** [comment]
the code snippet i posted has fixes for the wall stuff and colour stuff it just doesnt move more than one and causes other bugs
https://github.com/cdc143/CPSC-599/blob/master/EnemyMove

**Comment by cdc143** [comment]
I've got some other stuff to do, but I think part of the issue might be initEnemyLocation (or at least part of it)

**Comment by ksmort** [comment]
If you update the file and commit it I can take a look at the enemy move stuff?

**Comment by cdc143** [comment]
Check demo02-6. Just comment out the enemy movement stuff for now.

**Comment by lucmichaud** [comment]
merged 2-6 into 2-4
