### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by lucmichaud** [cdc143/CPSC-599#12]
Enemies only spawn inside the first room?

**Comment by ksmort** [comment]
And they spawn all over the place.   Needs to check for only spawning in available spaces and only a certain amount of them?

**Comment by lucmichaud** [comment]
its weird because it does an and with $07 so there should never be more and for spawning all over it checks for walls and doors and grabs a new location if they are one of those.  We tried checking for an open space an that just makes it go crazy

**Comment by cdc143** [comment]
I think the first issue is pretty easy to solve. Just add a call to
initEnemy everytime the room changes. The amount of enemies should be but
masked, but maybe there's some variable not getting reset when the player
moves floors. As for the not spawning on spaces, I think that's a recent
thing as it was working a couple commits ago

**Comment by ksmort** [comment]
I'll take a look at it.  Also, as the wall colour changes the enemy colours change every time you go down a level.  Happy coincidence.

**Comment by lucmichaud** [comment]
Yeah pretty sure we broke that when spawning enemies since we just used the wall colour lol

**Comment by ksmort** [comment]
:P  It works well though!

**Comment by ksmort** [comment]
Enemies should stop spawning over walls and doors now.

**Comment by lucmichaud** [comment]
odd thats what we tried first but it just made everything draw weird, seems to work now

**Comment by ksmort** [comment]
You might have forgotten the pound sign to access the header file?  That happens to me a lot.  Also, enemies should now be spawning in every room, but still kind of buggy (too many enemies in a room).

**Comment by lucmichaud** [comment]
I don't really understand how it gets too many sometimes, since it is definitely bit masking with 7

**Comment by lucmichaud** [comment]
I think i've stopped them from spawning tons of them but i still have them spawning under the screen so maybe mod isnt working?

**Comment by ksmort** [comment]
It might be something to do with lines 749-753?

inc enemyLoopCount
 lda enemyLoopCount
 cmp enemyCount
 bne initEnemyLoop
 rts

change bne to bpl or something like that.  It might be overwriting one of the counters, although that doesn't really make sense either.

**Comment by ksmort** [comment]
Lol, I'm behind, you already did that. :P

**Comment by lucmichaud** [comment]
yeah using absolutes on incrementing loops is generally bad

**Comment by ksmort** [comment]
It seems to be bug-free now.  There's just the problem of the enemies spawning in the status bars at the bottom of the screen.

**Comment by lucmichaud** [comment]
pretty sure that just means that my mod code is broken, i tried lowering the mod by a couple still didnt work

**Comment by ksmort** [comment]
It was doing that before but with the top status bar.  Perhaps the constraints need to be raised a bit?

**Comment by lucmichaud** [comment]
before it was because sometimes the level would draw itself down one row and leave empty space in the playfield

**Comment by cdc143** [comment]
So I tried out some enemy movement code, I've commented it out for now as it's not checking for collisions with walls or anything or clearing the previous enemy or remembering the color, but the enemies move in a semi random looking fashion toward the player at a reasonable speed (no faster than the player is able to move). I probably won't work on that much more cause I've got some other things to fix up, but its a nice start.

**Comment by ksmort** [comment]
Good start!  The huge snake of enemies coming at the player is kind of terrifying. :P

**Comment by ksmort** [comment]
In a good way

**Comment by lucmichaud** [comment]
Ok for spawning outside the map i put checks in to get new random numbers if they were greater than the boundaries and it still puts them outside sometimes, i feel like the vic is just bad XD

**Comment by cdc143** [comment]
For the player movement, are we literally drawing a space over where they
moved from or are we doing something smarter?

**Comment by cdc143** [comment]
Also, does getfrom screen return colour now?

**Comment by lucmichaud** [comment]
Pretty sure we just draw a space, ill make it return colour

edit: jk I changed that a while ago i guess, returns colour in drawColour

**Comment by ksmort** [comment]
Literally just a space.  For your sanity Luc, I modified it a bit when I was working on colour stuff so that it would return the colour so that I could get the colours for enemy/sword/player. :P

**Comment by cdc143** [comment]
Okay the enemy is no longer a snake. There's still some work to be done, but it is kind of fun rushing through the levels before this wall eating enemy gets you

**Comment by lucmichaud** [comment]
K the moving ones should now stay dead, also moved the enemy position arrays to the bottom of the file since w/e we were doing sometimes would mess up stuff under it

edit: they now spawn back at full hp, they were dieing off for a bit, not sure what happened
edit2: even when they do disappear you cant move into that spot
edit3: reverted the change

**Comment by cdc143** [comment]
There's probably something screwy with our branches, because it seems to
always want to increment either x or y

**Comment by cdc143** [comment]
Enemies move a lot better than they used to, and aren't getting stuck
anymore. However, they don't seem to die. Can we get the random colour
thing back?

**Comment by cdc143** [comment]
Okay so enemies can die now and they move pretty close to properly. They do
move off the walls and stuff as the player moves, so it's mostly okay.
Tried to readd the title in hex, but that screwed some stuff up. All in
all, it works pretty well. It actually makes for an alright game trying to
coral the enemies into one area so you can advance.

Feel free to make any changes to the readme or the code. I'll submit it
early tomorrow morning (at like 7).

On Dec 7, 2016 8:28 PM, "Christian Daniel" <cdc143@gmail.com> wrote:

Enemies move a lot better than they used to, and aren't getting stuck
anymore. However, they don't seem to die. Can we get the random colour
thing back?
