### ISSUE TITLE
Floor 4+

### ISSUE THREAD

**Issue by lucmichaud** [cdc143/CPSC-599#13]
after getting to floor 4 all the graphics are weird XD
![image](https://cloud.githubusercontent.com/assets/15695568/20951750/e7d1235e-bbe4-11e6-953f-0c9bfd3dc737.png)

**Comment by ksmort** [comment]
I was bitmasking with 0f, I'll change that back to 07 (I was trying to see if I could make invisible walls.  Nope. :P)

**Comment by ksmort** [comment]
Should be back to normal with the most recent commit, but lemme know if not (it's a simple fix).

**Comment by lucmichaud** [comment]
K got to level 12, colour and drawing still working fine
