### ISSUE TITLE
Level with half the screen filled with hearts

### ISSUE THREAD

**Issue by ksmort** [cdc143/CPSC-599#14]
I don't know if you guys have gotten this issue yet.  I'll try and get a screenshot when this happens again.

We could treat this level as a "lucky room" and just make sure we redraw the status bar whenever the player enters a new room?  It would be a lazy fix but not the worst thing...

**Comment by cdc143** [comment]
Fixed as well as large numbers of enemies in the room as far as I can tell (15 floors). Just cleared the carry flag before the addition in get random

**Comment by ksmort** [comment]
![error](https://cloud.githubusercontent.com/assets/10818279/20990723/86a9e42c-bc97-11e6-80c3-9e73babe05fe.png)

**Comment by ksmort** [comment]
Found it

**Comment by ksmort** [comment]
I changed the drawLives, hopefully that fixed things.
