### ISSUE TITLE
Heart drawing on playfield

### ISSUE THREAD

**Issue by lucmichaud** [cdc143/CPSC-599#15]
not sure what happened to the hearts drawing on the playfield
![image](https://cloud.githubusercontent.com/assets/15695568/20953527/a0a2bb84-bbf1-11e6-8f60-da78975d1896.png)

**Comment by ksmort** [comment]
line ~664 
putPotion: ;Assumes x coordinate and y coordinate to draw will be passed in
  lda #life_colour <----currently doesn't have a # in front of it, add the # in front and will work
  sta drawColour
  lda #lives_sprite
  jsr drawToPlayfield
  rts

I was going to fix it but don't want to get in the middle of the stuff you are doing.

**Comment by lucmichaud** [comment]
hmm put it in the latest build hearts no longer draw at all?

edit: I think I'm done the Symmetry for now lol

**Comment by lucmichaud** [comment]
ok I have a heart finally, but I feel like I was seeing them much more often before

**Comment by ksmort** [comment]
I think it might have just been luck that it was working, or the pound sign just disappeared.  Hearts works now.
