### ISSUE TITLE
2-6, 2-4

### ISSUE THREAD

**Issue by lucmichaud** [cdc143/CPSC-599#16]
can we merge the changes?

**Comment by ksmort** [comment]
What is the difference between the two?

**Comment by cdc143** [comment]
2-6 is everything I think. Unless you've changed 2-4 recently.

**Comment by lucmichaud** [comment]
k wasnt sure

**Comment by lucmichaud** [comment]
yeah it doesnt have the changes from just before the 2-6 commits
