### ISSUE TITLE
Title screen 

### ISSUE THREAD

**Issue by lucmichaud** [cdc143/CPSC-599#17]
Busted after new char stuff

**Comment by ksmort** [comment]
We need to transfer some of the letters over, or we can just use the p1 sprite and just not have a title :P

**Comment by cdc143** [comment]
Ya don’t worry about the title screen. I did’t move any alphabet characters over or update the title text. Everything else looks fine. I think I found why the issue. We have an sty enemyypos,x which doesn’t work, but if you move y to the accumulator, and do sea enemyypos,x, that works fine.

**Comment by lucmichaud** [comment]
its only eight letters to copy over

**Comment by cdc143** [comment]
I’ll do that later on. Not a huge deal to fix, just have to update all the header and stuff again. Enemyypos seems to be inited properly now, so maybe give your movement code a try again. The enemy does seem to move in a much more normal fashion now
