### ISSUE TITLE
Enemy goes to top left screen and gets stuck

### ISSUE THREAD

**Issue by ksmort** [cdc143/CPSC-599#18]
With recent updates.

**Comment by lucmichaud** [comment]
which is weird since we didnt change the way the AI chooses its direction

**Comment by ksmort** [comment]
Yeah, I don't know what's going on

**Comment by lucmichaud** [comment]
and they all go top left lol,

they don't only move up and left all the time though which doesnt help lol

**Comment by ksmort** [comment]
There is one that doesn't want to move either.  I'm done for a while, but hooray they are all moving!

**Comment by cdc143** [comment]
So enemyxpos and enemyypos are totally getting trashed somehow with huge values (look in monitor). Then the code asks if that’s a valid move, it obviously isn’t so it stops movement.
