### ISSUE TITLE
Checking for last col/row doesn't work

### ISSUE THREAD

**Issue by cdc143** [cdc143/CPSC-599#2]
I'm trying to get room switching working, and the col,row detection doesn't seem to work quite right. Check loadNewLevel for code

**Comment by ksmort** [comment]
Check demo02-3.  Something about col_end and the bottom parts for row don't work, but works (ish) for top half of the screen.

**Comment by cdc143** [comment]
This looks better, and we can load the levels randomly, but we have to keep track of which rooms we've already generated. That's what I was using the rooms variable and current rooms for. Basically we fill the room bytes with random numbers (1-4), the current room serves as an index (and is incremented and decremented when the player moves rooms). I don't know if that makes sense, but that's what I was hoping to get to.

**Comment by ksmort** [comment]
Totally!  I really like the idea, I just wasn't using it because I didn't fully understand it at the time.  Feel free to use whatever makes sense from 02-3, I was just fooling around with it for the most part!

**Comment by cdc143** [comment]
Okay so room switching basically works now. Still no bottom collision detection, so I didn't test the bottom doors, and we need to make sure the player spawns in the new room in the right location, but its coming together (demo02-02).

**Comment by ksmort** [comment]
See newest update to demo02-02.  Basically added drawing lives and enemies to screen to make demo02-02 look prettier, but also figured out why it is not drawing to bottom.  Should work now (see comments).  However, collision and collision_bot can be optimized into one subroutine, as a lot of the code is redundant.

**Comment by cdc143** [comment]
Okay room switching works well now. Just need to make sure the player is spawned in the right location. Also, we should switch rows and columns at some point later on because it gets confusing. I also want to make level loading into one routine, but we can do that after Thursday

**Comment by ksmort** [comment]
I'll switch row/col right now.

**Comment by ksmort** [comment]
Also, should we try out the code on the actual Vic-20 tomorrow?

**Comment by lucmichaud** [comment]
I have a couple hours free right now if we want to go try it out.

**Comment by ksmort** [comment]
I have class until 2, but we were thinking 2 ish if you are still available?

**Comment by lucmichaud** [comment]
i have tutorial from 2-4 XD, just go w/o me

**Comment by ksmort** [comment]
Haha, alright.  We'll let you know how it goes!

**Comment by ksmort** [comment]
So the game looks pretty good!  When the player tries to go off-screen it wraps around to the other side instead of just stopping, so we might want to consider walling the whole screen and let players advance only through doors, or have something to detect end-of-screen.
