### ISSUE TITLE
New Level design algorithm

### ISSUE THREAD

**Issue by cdc143** [cdc143/CPSC-599#3]
I took a look at the new level generation code. I really like the idea, but a few things I noticed

-I think we can do this with just three variables one for the row we're currently drawing (0-22), one to keep track of which byte of the row we're drawing (0-2) and one for an index into each byte (0-7). I think this is mostly what you intended, but some of the variables are confusingly named (there's really no need for columns here).

-I think we should store each row as 3 bytes. I know it's more memory, but you might very well want something in the middle of the level that's not at the edges (right now it just looks like you're cloning one byte 3 times to draw the row). We're only actually drawing 20 of the rows on screen (since we have one row on top for health and 2 on the bottom for inventory and other info). That gives us 8 level layouts in less than 500 bytes of ROM.

-Unrelated, but I think I'll try to work on enemy health and movement. You could probably do it in less, but I was thinking we have 2 bytes for position (x and y), and 1 byte to store things that how much damage they do and how much health they have. That's 3 bytes*4 enemies max per room=12 bytes

**Comment by ksmort** [comment]
Works for me!  Three bytes per row will still save lots of memory, especially if the algorithm is good!  

We could also store colour and enemy sprite in the byte for enemy information (i.e., literally use the byte of damage and health and plug that into colour and enemy sprite).  Kind of hacky and super lazy thought. :P

**Comment by cdc143** [comment]
I've updated the level code to use row abbr. It works, but it's still buggy. All the rows can be drawn, but they're not quite in the right place for some reason, so you get weird row fragments in places.
