### ISSUE TITLE
convertOffset subtraction not working

### ISSUE THREAD

**Issue by cdc143** [cdc143/CPSC-599#4]
I'm trying to convert an offset from graphics start into row and column, but my subtraction loop doesn't seem to be working for some reason (its in convertOffset). Do we already have code like this for the player somewhere?

**Comment by ksmort** [comment]
Did you fix the solution?  You could try looking into addCols and getRowColForm ir not

**Comment by cdc143** [comment]
Ya I fixed it after a long while. Realized I forgot to set the carry flag before doing the subtraction. Do we have a routine that draws something at a specific row/column (or converts row column back to an offset and then draws there)?

**Comment by ksmort** [comment]
The combo I tended to use was getRowColForm and drawTop/drawBottom/drawToScreenTop/drawToScreenBottom.  The subroutines should be towards the bottom of the code.

**Comment by cdc143** [comment]
I'm getting the row/column well, but when I try to move and draw and stuff, I can't get past the title screen. I'm kinda lost. Maybe take a look! probably something simple I'm missing. Most of the code is in initEnemyLocation and moveEnemy

**Comment by ksmort** [comment]
I'm pretty sure we can't get past the title screen is because we are out of
memory!  I haven't checked the code but that is the problem I have been
getting, which is why we need a new way of storing yhe levels.

**Comment by cdc143** [comment]
I tried deleting some of the level data from the copy I was working on, and that seems to work well. It still doesn't draw, but it seems to be changing the row and column okay. Our prg file is just over 3kb, so if we're already running out of ram, the vic must be loading all our code into ram and then executing, so apparently we don't have 20kb to store our code.
