### ISSUE TITLE
Going to down part of screen off by some x indices

### ISSUE THREAD

**Issue by ksmort** [cdc143/CPSC-599#5]
Probably has been figured out already, but going from top to bottom is off in index and the address drawing to just needs to be updated by something like 10 (just rough estimate).

**Comment by lucmichaud** [comment]
Not sure what this is referring to but check latest updates and see if it was fixed

**Comment by cdc143** [comment]
So sort of related, level drawing totally works now in the latest commit (yaay), but some of the offsets seem a little off. In particular, it doesn't draw to anywhere in the column x=0 unless you write something past where the end of screen should be (then you get something on the next row down). Just assemble and run the latest demo2-04 to see.

**Comment by lucmichaud** [comment]
pretty sure i fixed x=0 issue, needed a clc before addition

**Comment by lucmichaud** [comment]
you didnt pull before pushing >.>

**Comment by lucmichaud** [comment]
or hmm, my latest push is just gone

**Comment by ksmort** [comment]
Level drawing looks good!  One thing, probably because it hasn't been updated yet, is that when the human collides with an enemy, walls on the top are overwritten by a space.  I think that's just because the spaces are trying to blank out the hearts (because they currently aren't disappearing) but are one row too far down.

**Comment by lucmichaud** [comment]
the overwriting of the walls is because i moved the hearts up a row but didnt change the code that writes over the hearts when you take damage

**Comment by ksmort** [comment]
There's also a thing where the player can "move under" the top wall (player disappears). 

The game's looking good, guys!  Awesome job!

**Comment by cdc143** [comment]
Small bug I found. When I try to draw something to the 10th row (y=9) it screws up. Can draw to the 11th and 9th row just fine though
