### ISSUE TITLE
demo02-4.asm (734): Value in 'sty enemypos,x' must be <$100

### ISSUE THREAD

**Issue by ksmort** [cdc143/CPSC-599#9]
Won't compile.

**Comment by cdc143** [comment]
That's odd. Did you change anything? My latest commit of works fine for me.

**Comment by lucmichaud** [comment]
I get the same error

**Comment by cdc143** [comment]
I don't get the error. I think this was something we did in the lab, and it worked there as well. I realized we had one too many bytes in enemyxpos and enemyypos, so I changed that, but I'm not sure if that will fix it.

**Comment by cdc143** [comment]
If the error you're getting is exactly copied, the variable is called enemyypos not enemypos, so that could be it as well.

**Comment by lucmichaud** [comment]
after last commit still have an error
demo02-4.asm (734): error: Value in 'sty enemyypos,x' must be <$100.

**Comment by ksmort** [comment]
Same error (which was the same error as before, I misspelled it).

**Comment by cdc143** [comment]
Well I don't get the error and the game runs fine for me, so it's kinda
hard for me to debug. You could probably play around with the registers
(instead of using y, use x or the accumulator, since it doesn't seem to
complain about the line below it which is doing something basically
identical).

**Comment by lucmichaud** [comment]
update your header, fixed it for me

**Comment by cdc143** [comment]
It could also be a problem with what is in y although I doubt it, since
that's just a random number mod 16. But you could check that by just
storing y somewhere ($1000 is good because nothing else touches that) and
check it out in the monitor.

**Comment by ksmort** [comment]
Oh right, of course.  Compiles now, thanks!
